# Generated by Django 2.2 on 2019-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190710_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.TextField(max_length=100),
        ),
    ]
