# Generated by Django 2.2 on 2019-07-10 11:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190710_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=2),
        ),
    ]
