# Generated by Django 2.2 on 2019-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_plan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
