# Generated by Django 2.2 on 2019-11-22 13:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_member_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=account.models.Profile.get_default_image, upload_to='members'),
        ),
    ]
