# Generated by Django 2.2 on 2019-11-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191122_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_plan',
        ),
    ]
