# Generated by Django 2.2 on 2019-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_member_current_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_plan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
