# Generated by Django 2.2 on 2019-11-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_member_current_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_plan',
        ),
    ]
