# Generated by Django 2.2 on 2019-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0002_auto_20190704_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubMuscles',
        ),
    ]
