# Generated by Django 2.2 on 2019-07-06 14:49

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0003_delete_submuscles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='training_plan',
            name='slug',
        ),

        migrations.AddField(
            model_name='training_plan',
            name='days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='training_plan',
            name='excluded_equipment',
            field=models.ManyToManyField(blank=True, related_name='training_plans_without', to='training_plans.Equipment'),
        ),
        migrations.AddField(
            model_name='training_plan',
            name='frequenz',
            field=models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default=1, max_length=80),
        ),
        migrations.AddField(
            model_name='training_plan',
            name='kinds',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('endurance_training', 'Ausdauer'), ('muscle_building', 'Muskel/Kraftaufbau'), ('flexibility_training', 'Dehnung'), ('aeorobic', 'Aeorobic')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
