# Generated by Django 2.2 on 2019-07-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0004_auto_20190706_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='days',
        ),
    ]
