# Generated by Django 2.2 on 2019-07-06 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0005_remove_training_plan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
    ]
