# Generated by Django 2.2 on 2019-07-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0006_training_plan_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
    ]
