# Generated by Django 2.2 on 2019-07-07 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0007_remove_training_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
    ]
