# Generated by Django 2.2 on 2019-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0008_training_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=40, null=True)),
                ('kind_de', models.CharField(blank=True, max_length=40, null=True)),
                ('kind_en', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/exercise_kinds/')),
                ('identify', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sub_kind',
        ),
        migrations.RemoveField(
            model_name='training_plan',
            name='kinds',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='kind',
        ),
        migrations.AddField(
            model_name='training_plan',
            name='exercise_kinds',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='training_plans.Kind'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='kind',
            field=models.ManyToManyField(blank=True, default=None, related_name='exercises', to='training_plans.Kind'),
        ),
    ]
