# Generated by Django 2.2 on 2019-07-09 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0010_auto_20190709_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='frequenz_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='frequenz',
            field=models.CharField(choices=[('daily', 'Tag'), ('weekly', 'Woche'), ('monthly', 'Monat'), ('yearly', 'Jahr')], default=1, max_length=80),
        ),
    ]
