# Generated by Django 2.2 on 2019-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0011_auto_20190709_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_plan',
            name='frequenz',
            field=models.CharField(choices=[('daily', 'Tag'), ('weekly', 'Woche'), ('monthly', 'Monat'), ('yearly', 'Jahr')], default='weekly', max_length=80),
        ),
    ]
