# Generated by Django 2.2 on 2019-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0013_auto_20190710_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='kind',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor Geräte'), ('outdoor', 'Outdoor Geräte'), ('light', 'Leichte Geräte')], default='indoor', max_length=40),
        ),
        migrations.AddField(
            model_name='equipment',
            name='kind_de',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor Geräte'), ('outdoor', 'Outdoor Geräte'), ('light', 'Leichte Geräte')], default='indoor', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='kind_en',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor Geräte'), ('outdoor', 'Outdoor Geräte'), ('light', 'Leichte Geräte')], default='indoor', max_length=40, null=True),
        ),
    ]
