# Generated by Django 2.2 on 2019-07-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0014_auto_20190710_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='kind_de',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='kind_en',
        ),
    ]
