# Generated by Django 2.2 on 2019-07-10 11:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0015_auto_20190710_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='kind',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('indoor', 'Indoor Geräte'), ('outdoor', 'Outdoor Geräte'), ('light', 'Leichte Geräte')], max_length=20, null=True),
        ),
    ]
