# Generated by Django 2.2 on 2019-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0016_auto_20190710_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='kind',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor Geräte'), ('outdoor', 'Outdoor Geräte'), ('light', 'Leichte Geräte')], default='indoor', max_length=40, null=True),
        ),
    ]
