# Generated by Django 2.2 on 2019-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0017_auto_20190710_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eendurancetraining',
            name='area',
        ),
        migrations.RemoveField(
            model_name='eendurancetraining',
            name='sub_areas',
        ),
        migrations.RemoveField(
            model_name='emusclebuilding',
            name='area',
        ),
        migrations.AddField(
            model_name='exercise',
            name='area',
            field=models.CharField(blank=True, choices=[('arms', 'Arme'), ('chest', 'Brust'), ('legs', 'Beine'), ('back', 'Rücken'), ('glutes', 'Po'), ('bauch', 'Bauch'), ('Shoulder', 'Schultern')], default=1, max_length=40),
        ),
        migrations.DeleteModel(
            name='SubAreas',
        ),
    ]
