# Generated by Django 2.2 on 2019-07-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0018_auto_20190711_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='time',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='area',
            field=models.CharField(blank=True, choices=[('arms', 'Arme'), ('chest', 'Brust'), ('legs', 'Beine'), ('back', 'Rücken'), ('glutes', 'Po'), ('bauch', 'Bauch'), ('shoulder', 'Schultern'), ('full', 'Ganzkörper')], default=1, max_length=40),
        ),
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training_plans.Exercise'),
        ),
        migrations.AlterField(
            model_name='training',
            name='cool_down',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.CoolDown'),
        ),
        migrations.AlterField(
            model_name='training',
            name='warm_up',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.WarmUp'),
        ),
        migrations.AlterField(
            model_name='training',
            name='workout',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.Workout'),
        ),

        migrations.AddField(
            model_name='trainingsset',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plans.Training_plan'),
        ),
        migrations.AddField(
            model_name='trainingsset',
            name='trainings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plans.Training'),
        ),
    ]
