# Generated by Django 2.2 on 2019-07-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0021_auto_20190713_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='included_in', to='training_plans.Exercise')),
            ],
        ),
        migrations.AlterField(
            model_name='cooldown',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='cooldowns', to='training_plans.IncludedExercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training_plans.IncludedExercise'),
        ),
        migrations.AlterField(
            model_name='warmup',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='warmups', to='training_plans.IncludedExercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='training_plans.IncludedExercise'),
        ),
    ]
