# Generated by Django 2.2 on 2019-07-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0022_auto_20190713_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooldown',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='warmup',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='includedexercise',
            name='cool_down',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.CoolDown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='includedexercise',
            name='warm_up',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.WarmUp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='includedexercise',
            name='workout',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.Workout'),
            preserve_default=False,
        ),
    ]
