# Generated by Django 2.2 on 2019-07-14 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0023_auto_20190713_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
    ]
