# Generated by Django 2.2 on 2019-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0026_auto_20190714_2014'),
    ]
