# Generated by Django 2.2 on 2019-07-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0028_auto_20190714_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='trainings',
        ),
    ]
