# Generated by Django 2.2 on 2019-07-15 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0029_remove_training_plan_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='training_plans', through='training_plans.TrainingsSet', to='training_plans.Training'),
        ),

    ]
