# Generated by Django 2.2 on 2019-07-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0030_auto_20190715_1349'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='cooldown',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='set',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='warmup',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600)),
        ),
    ]
