# Generated by Django 2.2 on 2019-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0031_auto_20190715_1355'),
    ]

    operations = [

        migrations.AddField(
            model_name='training_plan',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
