# Generated by Django 2.2 on 2019-07-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0032_auto_20190715_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': []},
        ),

    ]
