# Generated by Django 2.2 on 2019-07-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0033_auto_20190715_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),

    ]
