# Generated by Django 2.2 on 2019-07-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0034_auto_20190715_2244'),
    ]

    operations = [

    ]
