# Generated by Django 2.2 on 2019-07-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0035_auto_20190722_1706'),
    ]

    operations = [

    ]
