# Generated by Django 2.2 on 2019-07-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0036_auto_20190723_0135'),
    ]

    operations = [

    ]
