# Generated by Django 2.2 on 2019-07-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0037_auto_20190723_1828'),
    ]

    operations = [

    ]
