# Generated by Django 2.2 on 2019-07-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0038_auto_20190725_0937'),
    ]

    operations = [

    ]
