# Generated by Django 2.2 on 2019-07-31 22:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_plans', '0039_auto_20190725_0944'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='exercise',
            name='like_percentage',
        ),

        migrations.CreateModel(
            name='CustomRating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3, validators=[
                 django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL, verbose_name='voter')),
            ],
        ),
    ]
