# Generated by Django 2.2 on 2019-07-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0040_auto_20190801_0038'),
    ]

    operations = [

    ]
