# Generated by Django 2.2 on 2019-07-31 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('training_plans', '0041_auto_20190801_0054'),
    ]

    operations = [


    ]
