# Generated by Django 2.2 on 2019-07-31 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0043_auto_20190801_0100'),
    ]

    operations = [

    ]
