# Generated by Django 2.2 on 2019-07-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0044_auto_20190801_0100'),
    ]

    operations = [


    ]
