# Generated by Django 2.2 on 2019-07-31 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('training_plans', '0045_auto_20190801_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrating',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='customrating',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
