# Generated by Django 2.2 on 2019-08-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0047_auto_20190801_0129'),
    ]

    operations = [

    ]
