# Generated by Django 2.2 on 2019-08-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0048_auto_20190803_0340'),
    ]

    operations = [
 

    ]
