# Generated by Django 2.2 on 2019-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0049_auto_20190818_0648'),
    ]

    operations = [

    ]
