# Generated by Django 2.2 on 2019-08-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0050_auto_20190818_0653'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='training_plan',
            name='trainings',
        ),

        migrations.DeleteModel(
            name='TrainingsSet',
        ),
    ]
