# Generated by Django 2.2 on 2019-08-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0051_auto_20190818_0656'),
    ]

    operations = [

        migrations.AddField(
            model_name='training_plan',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='training_plans.Training'),
        ),
    ]
