# Generated by Django 2.2 on 2019-08-18 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0052_auto_20190818_0658'),
    ]

    operations = [

        migrations.AlterField(
            model_name='training_plan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
