# Generated by Django 2.2 on 2019-08-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0053_auto_20190818_0707'),
    ]

    operations = [

        migrations.AlterField(
            model_name='training',
            name='cool_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.CoolDown'),
        ),
        migrations.AlterField(
            model_name='training',
            name='warm_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.WarmUp'),
        ),
        migrations.AlterField(
            model_name='training',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.Workout'),
        ),
    ]
