# Generated by Django 2.2 on 2019-08-18 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0054_auto_20190818_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooldown',
            name='duration',
        ),

        migrations.RemoveField(
            model_name='warmup',
            name='duration',
        ),

        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),

        migrations.AlterField(
            model_name='includedexercise',
            name='cool_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.CoolDown'),
        ),
        migrations.AlterField(
            model_name='includedexercise',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_siblings', to='training_plans.Exercise'),
        ),
        migrations.AlterField(
            model_name='includedexercise',
            name='warm_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.WarmUp'),
        ),
        migrations.AlterField(
            model_name='includedexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.Workout'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training_plans.IncludedExercise'),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
