# Generated by Django 2.2 on 2019-08-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0055_auto_20190818_0908'),
    ]

    operations = [

    ]
