# Generated by Django 2.2 on 2019-08-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0056_auto_20190821_0915'),
    ]

    operations = [

    ]
