# Generated by Django 2.2 on 2019-08-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0057_auto_20190821_0921'),
    ]

    operations = [

    ]
