# Generated by Django 2.2 on 2019-08-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0059_auto_20190821_1110'),
    ]

    operations = [

    ]
