# Generated by Django 2.2 on 2019-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0060_auto_20190821_1126'),
    ]

    operations = [

    ]
