# Generated by Django 2.2 on 2019-08-22 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0061_auto_20190821_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='unit',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[
                                      django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[
                                      django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
    ]
