# Generated by Django 2.2 on 2019-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0063_auto_20190822_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
