# Generated by Django 2.2 on 2019-08-22 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0064_training_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600), null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='reversrements',
            field=models.SmallIntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
    ]
