# Generated by Django 2.2 on 2019-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0065_auto_20190822_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='includedexercise',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='includedexercise',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
