# Generated by Django 2.2 on 2019-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0066_auto_20190822_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='set',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
