# Generated by Django 2.2 on 2019-08-22 15:53

from django.db import migrations, models
import training_plans.models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0067_auto_20190822_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_plan',
            name='exercise_kinds',
            field=models.ManyToManyField(blank=True, default=training_plans.models.Training_plan.fGetExerciseKindsList, related_name='training_plans', to='training_plans.Kind'),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
