# Generated by Django 2.2 on 2019-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0068_auto_20190822_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='often_used_kinds',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
