# Generated by Django 2.2 on 2019-09-07 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0069_training_plan_often_used_kinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='often_used_kinds',
        ),
        migrations.AddField(
            model_name='training_plan',
            name='kinds_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=13, null=True), size=4), blank=True, default=None, null=True, size=2),
        ),
    ]
