# Generated by Django 2.2 on 2019-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0070_auto_20190907_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='needed_equipment',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='training_plans.Equipment'),
        ),
    ]
