# Generated by Django 2.2 on 2019-09-14 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0071_training_plan_needed_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='kinds_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=25, null=True), size=4), blank=True, default=None, null=True, size=2),
        ),
    ]
