# Generated by Django 2.2 on 2019-09-16 17:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0072_auto_20190914_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
