# Generated by Django 2.2 on 2019-09-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0073_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipps',
            name='tipp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipps',
            name='tipp_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipps',
            name='tipp_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
