# Generated by Django 2.2 on 2019-09-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0074_auto_20190925_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='eStretching',
            fields=[
                ('exercise_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stretching', serialize=False, to='training_plans.Exercise')),
            ],
            bases=('training_plans.exercise',),
        ),
    ]
