# Generated by Django 2.2 on 2019-10-09 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0075_estretching'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='start_weight',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
