# Generated by Django 2.2 on 2019-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0076_exercise_start_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
    ]
