# Generated by Django 2.2 on 2019-10-09 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0077_exercise_cardio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True,
                                                  default=datetime.timedelta(seconds=1200), null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='training_plan',
            name='trainings',
        ),
        migrations.AddField(
            model_name='training',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='trainings', to='training_plans.Training_plan'),
        ),
        migrations.AlterField(
            model_name='training',
            name='cool_down',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='training', to='training_plans.CoolDown'),
        ),
        migrations.AlterField(
            model_name='training',
            name='warm_up',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='training', to='training_plans.WarmUp'),
        ),
        migrations.AlterField(
            model_name='training',
            name='workout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='training', to='training_plans.Workout'),
        ),
        migrations.AddField(
            model_name='includedexercise',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='exercises', to='training_plans.Interval'),
        ),
    ]
