# Generated by Django 2.2 on 2019-10-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0078_auto_20191009_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='status',
            field=models.CharField(choices=[(
                '0', 'Anfänger'), ('1', 'Erfahren'), ('2', 'Profi')], default='1', max_length=80),
        ),

        migrations.DeleteModel(
            name='Interval',
        ),
    ]
