# Generated by Django 2.2 on 2019-10-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0079_auto_20191009_2236'),
    ]

    operations = [

    ]
