# Generated by Django 2.2 on 2019-10-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0080_auto_20191009_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='includedexercise',
            name='interval',
        ),
    ]
