# Generated by Django 2.2 on 2019-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0081_remove_includedexercise_interval'),
    ]

    operations = [

    ]
