# Generated by Django 2.2 on 2019-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0082_auto_20191009_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='includedexercise',
            name='interval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='cardio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='training_plan',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Anfänger'), ('1', 'Erfahren'), ('2', 'Profi')], default='1', max_length=80, null=True),
        ),
    ]
