# Generated by Django 2.2 on 2019-10-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0083_auto_20191009_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_plan',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Männlich'), ('F', 'Weiblich')], max_length=100, null=True),
        ),
    ]
