# Generated by Django 2.2 on 2019-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0085_training_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedexercise',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
