# Generated by Django 2.2 on 2019-11-22 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_plans', '0086_auto_20191117_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='users',
        ),
        migrations.AddField(
            model_name='training_plan',
            name='favorite_from',
            field=models.ManyToManyField(blank=True, related_name='favorite_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
