# Generated by Django 2.2 on 2019-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0090_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_de',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='area_en',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
