# Generated by Django 2.2 on 2019-12-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0091_auto_20191224_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='area',
        ),
    ]
