# Generated by Django 2.2 on 2019-12-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0092_remove_exercise_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_plans.Area'),
        ),
    ]
