# Generated by Django 2.2 on 2019-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0094_training_areas_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('title_de', models.CharField(blank=True, max_length=40, null=True)),
                ('title_en', models.CharField(blank=True, max_length=40, null=True)),
                ('identify', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
