# Generated by Django 2.2 on 2019-12-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0095_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='kind',
        ),
        migrations.AddField(
            model_name='training',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training_plans.Goal'),
        ),
    ]
