# Generated by Django 2.2 on 2019-12-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0096_auto_20191229_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_plan',
            name='kinds_count',
        ),
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/training_goals/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/exercise_areas/'),
        ),
    ]
