# Generated by Django 2.2 on 2019-12-30 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0097_auto_20191230_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='workout_areas_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=25, null=True), size=2), blank=True, default=None, null=True, size=7),
        ),
    ]
