# Generated by Django 2.2 on 2019-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0098_training_workout_areas_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='area_weak',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
