# Generated by Django 2.2 on 2020-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0099_goal_area_weak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/exercise_muscles/')),
                ('identify', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emusclebuilding',
            old_name='sub_muscles',
            new_name='old_sub_muscles',
        ),
    ]
