# Generated by Django 2.2 on 2020-01-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0101_auto_20200105_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='emusclebuilding',
            name='sub_muscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercises', to='training_plans.Muscle'),
        ),
    ]
