# Generated by Django 2.2 on 2020-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0102_emusclebuilding_sub_muscles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emusclebuilding',
            name='old_sub_muscles',
        ),
        migrations.AlterField(
            model_name='emusclebuilding',
            name='muscle',
            field=models.CharField(blank=True, default='bizeps', max_length=200),
        ),
    ]
