# Generated by Django 2.2 on 2020-01-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0103_auto_20200105_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emusclebuilding',
            old_name='muscle',
            new_name='old_muscle',
        ),
    ]
