# Generated by Django 2.2 on 2020-01-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0104_auto_20200105_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='emusclebuilding',
            name='muscle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_from_exercises', to='training_plans.Muscle'),
        ),
    ]
