# Generated by Django 2.2 on 2020-01-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0105_emusclebuilding_muscle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emusclebuilding',
            name='old_muscle',
        ),
    ]
