# Generated by Django 2.2 on 2020-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0106_remove_emusclebuilding_old_muscle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleTrainingMuscleCombinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('muscles', models.ManyToManyField(blank=True, null=True, related_name='possible_training_groups', to='training_plans.Muscle')),
            ],
        ),
    ]
