# Generated by Django 2.2 on 2020-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0107_possibletrainingmusclecombinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/exercise_areas/')),
                ('identify', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='possibletrainingmusclecombinations',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='possible_training_groups', to='training_plans.Muscle'),
        ),
    ]
