# Generated by Django 2.2 on 2020-01-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0109_auto_20200105_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='muscles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscle_group', to='training_plans.Muscle'),
        ),
    ]
