# Generated by Django 2.2 on 2020-01-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0110_musclegroup_muscles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscles',
        ),
        migrations.AddField(
            model_name='muscle',
            name='muscle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='training_plans.MuscleGroup'),
        ),
    ]
