# Generated by Django 2.2 on 2020-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0111_auto_20200105_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibletrainingmusclecombinations',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='possible_training_groups', to='training_plans.MuscleGroup'),
        ),
    ]
