# Generated by Django 2.2 on 2020-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0112_auto_20200105_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibletrainingmusclecombinations',
            name='muscles_count',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
