# Generated by Django 2.2 on 2020-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0113_possibletrainingmusclecombinations_muscles_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='training_plans.MuscleGroup'),
        ),
    ]
