# Generated by Django 2.2 on 2020-01-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0114_training_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='benefit',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
    ]
