# Generated by Django 2.2 on 2020-01-14 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0115_musclegroup_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='muscles_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=25, null=True), size=2), blank=True, default=None, null=True, size=7),
        ),
        migrations.AddField(
            model_name='training',
            name='workout_muscles_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=25, null=True), size=2), blank=True, default=None, null=True, size=7),
        ),
    ]
